### PR TITLE
Russian translation - Fix one instance of plural forms

### LINKED ISSUE #1421: [TRANSLATION] [UI] Missing plural forms support
Here are all the instances (that I found) of translatable text that needs plural forms support:

./app/project/item/footage/audiostream.cpp: return QCoreApplication::translate("Stream", "%1: Audio - %2 Channels, %3Hz").arg(QString::number(index()),
./app/widget/nodeparamview/nodeparamviewarraywidget.cpp: count_lbl_->setText(tr("%1 elements").arg(array_->GetSize()));
./app/dialog/preferences/tabs/preferencesdisktab.cpp:  cache_ahead_slider_->SetFormat(tr("%1 seconds"));
./app/dialog/preferences/tabs/preferencesdisktab.cpp:  cache_behind_slider_->SetFormat(tr("%1 seconds"));
./app/dialog/preferences/tabs/preferencesgeneraltab.cpp:  default_still_length_->SetFormat(tr("%1 seconds"));
./app/task/project/import/import.cpp:  SetTitle(tr("Importing %1 files").arg(file_count_));

### PR DESCRIPTION
**Pull request by prokoudine**
Partially fixes #1421. Not sure about other instances yet.

### CODE REVIEW

**Comment by Simran-B** [comment]
#1424 is merged / #1421 resolved. You may update the .ts file with `lupdate` and translate the now available strings with a singular and two plural forms.

File: app/ts/ru_RU.ts [hunk 1]
```diff
@@ -241,6 +236,11 @@
         <source>%1: Video - %2x%3</source>
         <translation>%1: Видео - %2x%3</translation>
     </message>
+    <message>
+        <location filename="../project/item/footage/audiostream.cpp" line="34"/>
+        <source>%1: Audio - %2 Channel(s), %3Hz</source>
+        <translation type="unfinished"></translation>
```
Comment (Simran-B) [inline app/ts/ru_RU.ts:242]:
```suggestion
        <translation type="unfinished">%1: Звук - %2 каналов, %3 Гц</translation>
```

File: app/ts/ru_RU.ts [hunk 2]
```diff
@@ -614,253 +617,253 @@ Length: %4</source>
...
         <source>Importing...</source>
-        <translation type="unfinished"></translation>
+        <translation>Выполняется импорт…</translation>
     </message>
     <message>
-        <location filename="../core.cpp" line="321"/>
+        <location filename="../core.cpp" line="309"/>
         <source>Import footage...</source>
-        <translation type="unfinished"></translation>
+        <translation>Импортировать видеоматериал…</translation>
```
Comment (Simran-B) [inline app/ts/ru_RU.ts:637]: While ellipsis is typografically correct, the source string doesn't use it.
```suggestion
        <translation>Импортировать видеоматериал...</translation>
```

File: app/ts/ru_RU.ts [hunk 3]
```diff
@@ -614,253 +617,253 @@ Length: %4</source>
...
 
 Make sure a sequence is loaded and it has a connected Viewer node.</source>
         <translation type="unfinished"></translation>
     </message>
     <message>
-        <location filename="../core.cpp" line="900"/>
+        <location filename="../core.cpp" line="891"/>
         <source>Olive Project</source>
-        <translation type="unfinished"></translation>
+        <translation>Проект OIive</translation>
```
Comment (Simran-B) [inline app/ts/ru_RU.ts:783]:
```suggestion
        <translation>Проект Olive</translation>
```

**Comment by Simran-B** [comment]
Merging as-is, will do a follow-up commit to fix some issues.
